version: 1.0.{build}
image: Visual Studio 2022
before_build:
- cmd: nuget.exe restore ProteinDigestionSimulator.NET.sln
configuration: Release
platform: Any CPU
build:
  project: ProteinDigestionSimulator.NET.sln
  verbosity: minimal
artifacts:
- path: bin
  name: Protein-Digestion-Simulator